### ISSUE TITLE
Add Array based Algorithms

### ISSUE THREAD

**Issue by Mridul-1-Sharma** [Mridul-1-Sharma/data_structures_algos#1]

**Comment by OmkarDate29** [comment]
Can you assign this to me

**Comment by akhilender-bongirwar** [comment]
hey @Mridul-1-Sharma ,can you assign this to me.

**Comment by Rohit-R2000** [comment]
i can add all the operations which we can perform on an array like printing , inserting , deletion , etc .So can you please assign this issue to me

**Comment by Mridul-1-Sharma** [comment]
> i can add all the operations which we can perform on an array like printing , inserting , deletion , etc .So can you please assign this issue to me

ok assigned

**Comment by Mridul-1-Sharma** [comment]
> Can you assign this to me

assigned

**Comment by Mridul-1-Sharma** [comment]
> @Mridul-1-Sharma please assign me this, I would like to help

Assigned please contribute

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?

**Comment by akhilender-bongirwar** [comment]
Hi @Mridul-1-Sharma, Please merge my PR #23.

**Comment by Mridul-1-Sharma** [comment]
> Can you please assign this issue to me?

Ok assigned

**Comment by Mridul-1-Sharma** [comment]
> Hi @Mridul-1-Sharma, Please merge my PR #23.

Merged

**Comment by kcirnez1211** [comment]
Hi @Mridul-1-Sharma , Can you please assign me this. I would like to contribute.

**Comment by Mridul-1-Sharma** [comment]
> Hi @Mridul-1-Sharma , Can you please assign me this. I would like to contribute.

ok
