### ISSUE TITLE
Single Operation Part 2 : CODECHEF STARTERS 60 SOLUTION

### ISSUE THREAD

**Issue by sahilsrivastava25** [Mridul-1-Sharma/data_structures_algos#21]
@Mridul-1-Sharma 
I would like to contribute this problem in your repository. Also I will be really grateful to you if you tag this as Hacktoberfest 2022 contribution.

**Comment by sahilsrivastava25** [comment]
@Mridul-1-Sharma Kindly assign me this issue.

**Comment by Mridul-1-Sharma** [comment]
> @Mridul-1-Sharma Kindly assign me this issue.

Assigned
