### ISSUE TITLE
Create an arrayLinkedList

### ISSUE THREAD

**Issue by JunJul** [Mridul-1-Sharma/data_structures_algos#40]
I can use the array not the vector that one to create a singly linked list. The purpose for this is to compare the array to the linked list. How are they different?

**Comment by JunJul** [comment]
Hi, @Mridul-1-Sharma . Could you assign this task to me and add a hacktoberfest label for me?

**Comment by Mridul-1-Sharma** [comment]
> Hi, @Mridul-1-Sharma . Could you assign this task to me and add a hacktoberfest label for me?

Please elaborate the issue

**Comment by JunJul** [comment]
An array has pop, top, insert operations that are similar to a stack
