### ISSUE TITLE
Add two more functions for arrayList class

### ISSUE THREAD

**Issue by JunJul** [Mridul-1-Sharma/data_structures_algos#48]
I want to add a remove(T elem) function which users can remove a specific element in the list, and also compare this to the linked List.

**Comment by JunJul** [comment]
@Mridul07Sharma please assign me this task and add me a Hacktoberfest label, thank u.

**Comment by JunJul** [comment]
More detail will be in the pull request.

**Comment by Mridul-1-Sharma** [comment]
ok
